services:
  worker:
    image: ghcr.io/planktoscope/device-backend-processing-segmenter:pr-74
    ports:
      - 8001:8001
    volumes:
      - ./machine-name:/run/machine-name
      - ~/.local/share/planktoscope/data:/home/pi/data
      - ~/.local/share/planktoscope/device-backend-logs:/home/pi/device-backend-logs
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      bind-mount-setup:
        condition: service_completed_successfully
  bind-mount-setup:
    image: docker.io/library/alpine:3.21.3
    volumes:
      - ~/.local/share/planktoscope/data:/home/pi/data
      - ~/.local/share/planktoscope/device-backend-logs:/home/pi/device-backend-logs
    command: 'sh -c "chown -R 1000:1000 /home/pi/data /home/pi/device-backend-logs"'
