services:
  server:
    image: filebrowser/filebrowser:v2.27.0
    ports:
      - 9000:80
    volumes:
      - ~/.local/share/planktoscope/data/:/home/pi/data/
      - ~/.local/share/planktoscope/data/:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/data
      - FB_PORT=80 # for some reason filebrowser doesn't work if this is port 8080
      - FB_NOAUTH=true

volumes:
  server-data: {}
