services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.32.0
    ports:
      - 9000:9000
    volumes:
      - ~/.local/share/planktoscope/data:/home/pi/data
      - ~/.local/share/planktoscope/data:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/data
      # We must assign a port which is available to non-root users:
      - FB_PORT=9000
      - FB_NOAUTH=true
    user: '1000:1000'
    depends_on:
      volume-setup:
        condition: service_completed_successfully
  volume-setup:
    image: docker.io/library/alpine:3.21.3
    volumes:
      - server-data:/database
    command: 'sh -c "chown -R 1000:1000 /database"'

volumes:
  server-data: {}
